# Common Server Configuration
server:
  port: 8080
  servlet:
    context-path: /game
  tomcat:
    max-connections: 20000
    max-threads: 800
    accept-count: 800

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/game?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456789

mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:/mapper/*.xml