# Common Server Configuration
server:
  port: 8085
  servlet:
    context-path: /game
  tomcat:
    max-connections: 20000
    max-threads: 800
    accept-count: 800

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/game?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456789
  jpa:
    show-sql: true

mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:/mapper/*.xml

logging:
  level:
    org:
      springframework: WARN
    com:
      example:
        game:
          dao: DEBUG
  file:
    name: logs/spring-boot-logging.log